### ISSUE TITLE
Do you have any plan to release source code for Linux platform?

### ISSUE THREAD

**Issue by yhuanghamu** [SunsetQuest/CudaPAD#1]
I believe your project is amazing, but my server run on Linux.

**Comment by SunsetQuest** [comment]
Thank you Steven. That is really nice to hear.  =) 

I wish I could answer yes, but there are no plans for the Linux platform.  This is Partially because I am not experienced in Linux but also because I don't have time. I built this as a tool for myself to program my AI on GPUs and got a little carried away so I decided to publish it. If anyone wants to adopt the program for linux they are welcome to. (That would be a big project though as not much of the code would be reusable.)

BTW - I will be at the GPU technology conference. I will have a poster there and will be presenting it(not sure what that entails though).

**Comment by nevion** [comment]
@yhuanghamu any chance this can be revisited?
